name: BigBrother
main: shoghicp\BigBrother\BigBrother
load: STARTUP
author: BigBrotherTeam
version: 1.6.0-beta
api: [5.0.0]
description: "Allows the connection of Minecraft: PC clients to PocketMine-MP servers"
website: https://github.com/BigBrotherTeam/BigBrother
mcpe-protocols: [544, 545, 554, 557]